version: '2'
services:
  postgres:
    image: timescale/timescaledb:latest-pg12
    volumes:
      - $HOME/developer/astra/postgresql:/var/lib/postgresql/data
    ports:
      - 127.0.0.1:5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
    container_name: local-timescale
    networks:
      - localNetwork
  redis:
    image: redis
    ports:
      - 6379:6379
    container_name: local-redis
    networks:
      - localNetwork
networks:
  localNetwork: